get http://localhost:3000/events


###
get http://localhost:3000/events/show/:id

###
post http://localhost:3000/events/create
Content-Type: application/json

{

        
            "Name": "marathon",
            "Type": "sport",
            "Free": "False",
            "Price": 150,
            "Date_event": "10/12/2020",
            "Date_fin_event": "11/12/2020",
            "Heure_debut": "10.00",
            "Lieu": "la goulette",
            "Nbr_place": "150",
            "Image": "fdser",
            "Nom_Club": "281098235_532837978428890_4367202906646536400_n.jpg"
        
}

###

post http://localhost:3000/events/update/:id


###

get http://localhost:3000/events/delete/:id



