 ### (getAllPayments)
get http://localhost:3000/payments


### (getPaymentById)

get http://localhost:3000/payments/62deaef6fe152d7fa43d8dea



### (deletePayment)

get http://localhost:3000/payments/delete/62c9cee9ec3716ede6f6ef8e


### (updatePayment) do not use this route : payments auto from stripe

post http://localhost:3000/payments/update/62c9ac24d90f07298624a450
Content-Type: application/json

{
    "email" : "effacer",
    "nom" : "effacer@outlook.fr",
    "montantPaye" : "6969"
}
