### user with valid token (getAllUsers)
get http://localhost:3000/users

### user with valid token (getUserById)
get http://localhost:3000/users/62daf155c0da94bbb00b735b
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlY29uZEBvdXRsb29rLmZyIiwidXNlcklkIjoiNjJjNDU0NzBmYmQ1YTM5NGQ2NjJkZTgwIiwiYWNjb3VudFR5cGUiOiJQcm9mZXNzZXVyIiwiaWF0IjoxNjU3MzAzNTk2LCJleHAiOjE2NTczMDcxOTZ9.HpotE8LvKocROjxR3f2HB7oZVgaOYuKJgX4GCh_mGIU

### (createUser)
post http://localhost:3000/users/create
Content-Type: application/json

{
       "userName" : "haroun",
       "email" : "haroun@gmail.com",
       "password" : "haroun",
       "verifyPassword": "haroun ",
       "accountType" :"haroun" ,
       "questionSecurite" :"haroun",
       "reponseQuestionSecurite" :"haroun",
       "nom" :"haroun",
       "prenom" :"haroun",
       "dateDeNaissance":"haroun",
       "adresse" :"haroun",
       "isActive":"haroun",
       "classe" :"haroun",
       "club" :"haroun",
       "specialite":"haroun"
}

### admin with valid token (deleteUser)
get http://localhost:3000/users/delete/62db2f8dffb3cf85b68b7876
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9uZW9uZUBlc3ByaXQudG4iLCJ1c2VySWQiOiI2MmRhZTczNmNjYzkwZGMzMmNlODZkMGEiLCJhY2NvdW50VHlwZSI6ImFkbWluIiwibm9tIjoiSGFtZGkiLCJwcmVub20iOiJNb2hhbWVkIEFtaW5lIiwiaWF0IjoxNjU4NTEzMzA4LCJleHAiOjE2NTg1MTY5MDh9.oRlad3rfagEZTJLn8wVn4I-sANCQ69tggrb5t2NWGNs

### user with valid token (updateUser)
post http://localhost:3000/users/update/62daccc8bb9c72e1d53dc6ba
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG91dGxvb2suZnIiLCJ1c2VySWQiOiI2MmM5NWM1ZGQ5NDcyYWEzOGJjYmM1YjEiLCJhY2NvdW50VHlwZSI6ImFkbWluIiwibm9tIjoiSGFtZGkiLCJwcmVub20iOiJNb2hhbWVkIEFtaW5lIiwiaWF0IjoxNjU3NDcyNjE5LCJleHAiOjE2NTc0NzYyMTl9.4jd_NB-tpKcmIwgqm7ELxdkws69e93Ph_sJEFjljZkY
Content-Type: application/json

{
       "userName" : "zied",
       "email" : "hedhiri.zied@esprit.tn",
       "password" : "zied",
       "verifyPassword": "zied",
       "accountType" :"Professeur" ,
       "questionSecurite" :"pet",
       "reponseQuestionSecurite" :"milou",
       "nom" :"Hamdi",
       "prenom" :"Mohamed Amine",
       "dateDeNaissance":"28-12-1989",
       "adresse" :"2011 denden",
       "classe" :"2CINFO 02",
       "club" :"ESPRIT SPACE",
       "specialite":"BI", 
       "isActive" :true
}

### authorization + get a token(logIn)
post http://localhost:3000/users/login
Content-Type: application/json

{
       "email" : "oneonpppprit.tn",
       "password" : "pppp"
}


###
get http://localhost:3000/users/eleve

###

get http://localhost:3000/users/professeur



































###

post http://localhost:3000/notes/create
Content-Type: application/json

{
"Designation" : "FR",
"nomEnseignant" : "MELEK",
"noteCc" : "20"
}

###
post  http://localhost:3000/notes/update/62cf02f66d6eb7df1e689a95

{
"Designation" : "FR",
"nomEnseignant" : "MELEK",
"noteCc" : "20"
}

###
get http://localhost:3000/notes/

###
 
get http://localhost:3000/notes/delete/62cf02f66d6eb7df1e689a95

###

get http://localhost:3000/pdf/62cf09bc1a283186beb43b2b